title: KNVB afdeling voetbalonderzoek
logo: https://sassets.knvb.nl/sites/knvb.nl/files/knvb.svg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
