title: KNVB afdeling voetbalonderzoek
logo: https://sassets.knvb.nl/sites/knvb.nl/files/knvb.svg
description: <h3>Over Ons</h3><p>Team voetbalonderzoek is het kenniscentrum van de afdeling voetbal. Samen zorgen we voor een onderbouwde, objectieve en geïnformeerde besluitvorming op voetbaltechnische thema’s zowel voor top als breedte en de kennisdeling hierover binnen en buiten de organisatie.</p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
